//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InentorySystem.ProductReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductReference.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: Generating message contract since element name product from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        InentorySystem.ProductReference.AddProductResponse AddProduct(InentorySystem.ProductReference.AddProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<InentorySystem.ProductReference.AddProductResponse> AddProductAsync(InentorySystem.ProductReference.AddProductRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        InentorySystem.ProductReference.GetStatusResponse GetStatus(InentorySystem.ProductReference.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<InentorySystem.ProductReference.GetStatusResponse> GetStatusAsync(InentorySystem.ProductReference.GetStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProduct", Namespace="http://tempuri.org/", Order=0)]
        public InentorySystem.ProductReference.AddProductRequestBody Body;
        
        public AddProductRequest() {
        }
        
        public AddProductRequest(InentorySystem.ProductReference.AddProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string product;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal price;
        
        public AddProductRequestBody() {
        }
        
        public AddProductRequestBody(string product, int quantity, decimal price) {
            this.product = product;
            this.quantity = quantity;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public InentorySystem.ProductReference.AddProductResponseBody Body;
        
        public AddProductResponse() {
        }
        
        public AddProductResponse(InentorySystem.ProductReference.AddProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddProductResult;
        
        public AddProductResponseBody() {
        }
        
        public AddProductResponseBody(string AddProductResult) {
            this.AddProductResult = AddProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="http://tempuri.org/", Order=0)]
        public InentorySystem.ProductReference.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(InentorySystem.ProductReference.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public InentorySystem.ProductReference.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(InentorySystem.ProductReference.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStatusResult;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(string GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : InentorySystem.ProductReference.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<InentorySystem.ProductReference.ProductServiceSoap>, InentorySystem.ProductReference.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InentorySystem.ProductReference.AddProductResponse InentorySystem.ProductReference.ProductServiceSoap.AddProduct(InentorySystem.ProductReference.AddProductRequest request) {
            return base.Channel.AddProduct(request);
        }
        
        public string AddProduct(string product, int quantity, decimal price) {
            InentorySystem.ProductReference.AddProductRequest inValue = new InentorySystem.ProductReference.AddProductRequest();
            inValue.Body = new InentorySystem.ProductReference.AddProductRequestBody();
            inValue.Body.product = product;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            InentorySystem.ProductReference.AddProductResponse retVal = ((InentorySystem.ProductReference.ProductServiceSoap)(this)).AddProduct(inValue);
            return retVal.Body.AddProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InentorySystem.ProductReference.AddProductResponse> InentorySystem.ProductReference.ProductServiceSoap.AddProductAsync(InentorySystem.ProductReference.AddProductRequest request) {
            return base.Channel.AddProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<InentorySystem.ProductReference.AddProductResponse> AddProductAsync(string product, int quantity, decimal price) {
            InentorySystem.ProductReference.AddProductRequest inValue = new InentorySystem.ProductReference.AddProductRequest();
            inValue.Body = new InentorySystem.ProductReference.AddProductRequestBody();
            inValue.Body.product = product;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            return ((InentorySystem.ProductReference.ProductServiceSoap)(this)).AddProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InentorySystem.ProductReference.GetStatusResponse InentorySystem.ProductReference.ProductServiceSoap.GetStatus(InentorySystem.ProductReference.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public string GetStatus(string name) {
            InentorySystem.ProductReference.GetStatusRequest inValue = new InentorySystem.ProductReference.GetStatusRequest();
            inValue.Body = new InentorySystem.ProductReference.GetStatusRequestBody();
            inValue.Body.name = name;
            InentorySystem.ProductReference.GetStatusResponse retVal = ((InentorySystem.ProductReference.ProductServiceSoap)(this)).GetStatus(inValue);
            return retVal.Body.GetStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InentorySystem.ProductReference.GetStatusResponse> InentorySystem.ProductReference.ProductServiceSoap.GetStatusAsync(InentorySystem.ProductReference.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<InentorySystem.ProductReference.GetStatusResponse> GetStatusAsync(string name) {
            InentorySystem.ProductReference.GetStatusRequest inValue = new InentorySystem.ProductReference.GetStatusRequest();
            inValue.Body = new InentorySystem.ProductReference.GetStatusRequestBody();
            inValue.Body.name = name;
            return ((InentorySystem.ProductReference.ProductServiceSoap)(this)).GetStatusAsync(inValue);
        }
    }
}
